baseURL = 'https://graphbench.example.com/'
locale = 'en-us'
title = 'Graph Learning Benchmarks'

[params]
  description = "Leaderboards for graph learning benchmarks"
  chartjsCDN = "https://cdn.jsdelivr.net/npm/chart.js@4"
  repoURL = "https://github.com/martinalex000/benchmarking_website"

[taxonomies]
  benchmark = "benchmarks"
  domain = "domains"
  task_type = "task_types"

[outputs]
  home = ["HTML", "JSON"]
  section = ["HTML", "JSON"]
  page = ["HTML"]

[markup.goldmark.renderer]
  unsafe = true
